package com.cqxb.base;

import com.cqxb.until.PinyinUtils;

//THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTRACTS.
 */
public class Contact implements Comparable {

	private Long id;
	private String uid;
	private String fid;
	private String fname;
	private String pingyin;
	private String phone;
	private Integer is_friend;
	private Integer is_member;

	public Contact() {
	}

	public Contact(Long id) {
		this.id = id;
	}

	public Contact(Long id, String uid, String fid, String fname,
			String phone, Integer is_friend, Integer is_member) {
		this.id = id;
		this.uid = uid;
		this.fid = fid;
		this.fname = fname;
		this.phone = phone;
		this.is_friend = is_friend;
		this.is_member = is_member;
		this.pingyin = PinyinUtils.getPingYin(fname);
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUid() {
		return uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getFname() {
		return fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Integer getIs_friend() {
		return is_friend;
	}

	public void setIs_friend(Integer is_friend) {
		this.is_friend = is_friend;
	}

	public Integer getIs_member() {
		return is_member;
	}

	public void setIs_member(Integer is_member) {
		this.is_member = is_member;
	}

	@Override
	public int compareTo(Object another) {
		if (pingyin == null || pingyin.length() == 0) {
			pingyin = PinyinUtils.getPingYin(fname);
		}
		if (((Contact) another).pingyin == null
				|| ((Contact) another).pingyin.length() == 0) {
			((Contact) another).pingyin = PinyinUtils
					.getPingYin(((Contact) another).fname);
		}
		return pingyin.compareTo(((Contact) another).pingyin);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (null != obj && obj instanceof Contact) {
			Contact p = (Contact) obj;
			if (fname.equals(p.fname) && phone.equals(p.phone)) {
				return true;
			}
		}
		return false;
	}

	@Override
	public int hashCode() {
		return (this.fname + this.phone).hashCode();
	}

}
